name: "hsrb"
joint_model_group_name: "arm"
frame_id: "odom"
global_link_transform: "hand_palm_link"
scene_collision_group_name: ""
tip_to_gripper_offset:
  x: 0.08
  y: 0.0
  z: 0.0
gripper_to_base_rot_offset:
  x: 0.707
  y: 0.0
  z: 0.707
  w: 0.0
# from src/hsrb_moveit/hsrb_moveit_config/config/hsrb.srdf
neutral_pos_joint_names:
  - "arm_lift_joint"
  - "arm_flex_joint"
  - "arm_roll_joint"
  - "wrist_flex_joint"
  - "wrist_roll_joint"
neutral_pos_values:
  - 0.2
  - -0.7
  - 0.0
  - -1.2
  - 0.0
base_cmd_topic: "/hsrb/command_velocity"
base_vel_rng: 0.2
base_rot_rng: 1.5
z_min: 0.2
z_max: 1.4
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.1
gmm_base_offset: 0.25
# not used
kinematics_solver_timeout: 0.0
# NOTE: approximation, rather a circle than a square
# values inferred from https://www.brain.kyutech.ac.jp/~hma/robots/hsr/
robot_base_size_meters:
  x: 0.43
  y: 0.43
#initial_joint_values:
