name: "pr2"
joint_model_group_name: "right_arm"
frame_id: "odom_combined"
global_link_transform: "r_wrist_roll_link"
scene_collision_group_name: ""
tip_to_gripper_offset:
  x: 0.18
  y: 0.0
  z: 0.0
gripper_to_base_rot_offset:
  x: 0
  y: 0
  z: 0
  w: 1
neutral_pos_joint_names:
  - "r_shoulder_pan_joint"
  - "r_shoulder_lift_joint"
  - "r_upper_arm_roll_joint"
  - "r_elbow_flex_joint"
  - "r_forearm_roll_joint"
  - "r_wrist_flex_joint"
  - "r_wrist_roll_joint"
neutral_pos_values:
  - 0.359647
  - 1.22538
  - 0.0
  - -1.59997
  - 2.34256
  - -0.513323
  - -2.41144
# https://github.com/uu-isrc-robotics/uu-isrc-robotics-pr2-pkgs/blob/master/pr2_control_utilities/src/pr2_control_utilities/pr2_planning.py
# "r_gripper_tool_joint", "r_gripper_palm_joint", "r_gripper_led_joint", "r_gripper_motor_accelerometer_joint"
base_cmd_topic: "/base_controller/command"
base_vel_rng: 0.2
base_rot_rng: 1.0
z_min: 0.2
z_max: 1.2
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.0
gmm_base_offset: 0.02
kinematics_solver_timeout: 0.01
# pr2_navigation/pr2_navigation_config/move_base/move_base_params.yaml
robot_base_size_meters:
  x: 0.65
  y: 0.65
# non-default joint values used in the simulator
initial_joint_values:
  bl_caster_rotation_joint: -0.000019
  br_caster_l_wheel_joint: -0.016590
  fl_caster_r_wheel_joint: 0.016280
  torso_lift_joint: 0.011498
  l_shoulder_pan_joint: 2.076015
  l_elbow_flex_joint: -1.75
  l_wrist_roll_joint: 0.000035
  r_shoulder_lift_joint: 0.000448
  r_forearm_roll_joint: 0.000602
  r_gripper_l_finger_joint: 0.002207
  bl_caster_l_wheel_joint: -0.023353
  br_caster_r_wheel_joint: -0.015209
  fr_caster_l_wheel_joint: 0.026865
  head_pan_joint: 0.002320
  l_shoulder_lift_joint: 1.249067
  l_forearm_roll_joint: -0.000298
  l_gripper_l_finger_joint: 0.002097
  r_upper_arm_roll_joint: -0.004287
  r_wrist_flex_joint: -0.466909
  bl_caster_r_wheel_joint: -0.023089
  fl_caster_l_wheel_joint: 0.008998
  fr_caster_r_wheel_joint: 0.029978
  head_tilt_joint: 0.224876
  l_upper_arm_roll_joint: 2.103466
  l_wrist_flex_joint: -0.196455
  r_shoulder_pan_joint: -0.000135
  r_elbow_flex_joint: -0.334197
  r_wrist_roll_joint: 0.000129
