#!/usr/bin/env python3
# EASY-INSTALL-ENTRY-SCRIPT: 'opendr-perception==1.0.0','console_scripts','face_recognition'
__requires__ = 'opendr-perception==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('opendr-perception==1.0.0', 'console_scripts', 'face_recognition')()
    )
