from opendr.perception.object_detection_2d.ssd.ssd_learner import SingleShotDetectorLearner
from opendr.perception.object_detection_2d.retinaface.retinaface_learner import RetinaFaceLearner
from opendr.perception.object_detection_2d.centernet.centernet_learner import CenterNetDetectorLearner
from opendr.perception.object_detection_2d.centernet.detr.detr_learner import DetrLearner
from opendr.perception.object_detection_2d.retinaface.yolov3.yolov3_learner import YOLOv3DetectorLearner

from opendr.perception.object_detection_2d.datasets import transforms