#!/usr/bin/env python3
# EASY-INSTALL-ENTRY-SCRIPT: 'opendr-simulation==1.0.0','console_scripts','human_model_generation_client'
__requires__ = 'opendr-simulation==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('opendr-simulation==1.0.0', 'console_scripts', 'human_model_generation_client')()
    )
