from opendr.perception.speech_recognition.quadraticselfonn.quadraticselfonn_learner import QuadraticSelfOnnLearner
from opendr.perception.speech_recognition.matchboxnet.matchboxnet_learner import MatchboxNetLearner
from opendr.perception.speech_recognition.edgespeechnets.edgespeechnets_learner import EdgeSpeechNetsLearner

__all__ = ['QuadraticSelfOnnLearner', 'MatchboxNetLearner', 'EdgeSpeechNetsLearner']
