Network: TANet      # RefineDet ...


# config for extracting the voxel feature with TA module
TA:

    INPUT_C_DIM: 9
    BOOST_C_DIM: 64  # or 32
    NUM_POINTS_IN_VOXEL: 100
    REDUCTION_R: 8
    # Note: Our released model need set " USE_PACA_WEIGHT: False"
    # When training model, setting " USE_PACA_WEIGHT: True" may be more stable
    USE_PACA_WEIGHT: False #True

PSA:
    C_Bottle: 128
    C_Reudce: 32





