name: "tiago"
joint_model_group_name: "arm_torso"
frame_id: "odom"
global_link_transform: "arm_tool_link"
scene_collision_group_name: ""
tip_to_gripper_offset:
  x: 0.205
  y: 0.0
  z: 0.0
gripper_to_base_rot_offset:
  x: -0.706825
  y: 0
  z: 0
  w: 0.707388
# from src/tiago_robot/tiago_bringup/config/motions/tiago_motions.yaml.em
neutral_pos_joint_names:
  - "torso_lift_joint"
  - "arm_1_joint"
  - "arm_2_joint"
  - "arm_3_joint"
  - "arm_4_joint"
  - "arm_5_joint"
  - "arm_6_joint"
  - "arm_7_joint"
# tucked in position: { 0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0 },
# holding gripper slightly in front of itself: { 0.19, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0 },
# what the first ik solution gives when initialised to {0.19, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0}: { 0.0841055, 1.43298, -0.925849, -2.88694, 1.8711, -1.48989, 1.39372, 1.40779 },
# {9.45119877e-02,  1.91752664e+00,  8.18002226e-01, 3.67928285e-01,  1.80674524e+00,  1.91897091e-01, -1.38597407e+00, 1.68665794e+00},
# straight in front of itself:{0.0, 3.14159265359 / 2, -0.0, -0.0, 0.0, -0.0, 0.0, 3.14159265359 / 2},
# angewinkelt vor sich: { 0.19, 1.1, 0.0, -1.0, 2.0, 1.2, 0.0, 0.0 }
neutral_pos_values:
  - 0.19
  - 1.1
  - 0.0
  - -1.0
  - 2.0
  - 1.2
  - 0.0
  - 0.0
base_cmd_topic: "/mobile_base_controller/cmd_vel"
base_vel_rng: 0.2
base_rot_rng: 0.4
z_min: 0.2
z_max: 1.5
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.1
gmm_base_offset: 0.0
kinematics_solver_timeout: 0.05
#pmb2_robot/pmb2_description/urdf/base/footprint
#NOTE: approximation, actually a circle of radius 0.27, not a square
robot_base_size_meters:
  x: 0.54
  y: 0.54
#initial_joint_values:
