// Generated by gencpp from file ros_bridge/OpenDRPose2D.msg
// DO NOT EDIT!


#ifndef ROS_BRIDGE_MESSAGE_OPENDRPOSE2D_H
#define ROS_BRIDGE_MESSAGE_OPENDRPOSE2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_bridge/OpenDRPose2DKeypoint.h>

namespace ros_bridge
{
template <class ContainerAllocator>
struct OpenDRPose2D_
{
  typedef OpenDRPose2D_<ContainerAllocator> Type;

  OpenDRPose2D_()
    : header()
    , pose_id(0)
    , conf(0.0)
    , keypoint_list()  {
    }
  OpenDRPose2D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose_id(0)
    , conf(0.0)
    , keypoint_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _pose_id_type;
  _pose_id_type pose_id;

   typedef float _conf_type;
  _conf_type conf;

   typedef std::vector< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >::other >  _keypoint_list_type;
  _keypoint_list_type keypoint_list;





  typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> const> ConstPtr;

}; // struct OpenDRPose2D_

typedef ::ros_bridge::OpenDRPose2D_<std::allocator<void> > OpenDRPose2D;

typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2D > OpenDRPose2DPtr;
typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2D const> OpenDRPose2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_bridge::OpenDRPose2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_bridge::OpenDRPose2D_<ContainerAllocator1> & lhs, const ::ros_bridge::OpenDRPose2D_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose_id == rhs.pose_id &&
    lhs.conf == rhs.conf &&
    lhs.keypoint_list == rhs.keypoint_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_bridge::OpenDRPose2D_<ContainerAllocator1> & lhs, const ::ros_bridge::OpenDRPose2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88f7162365f7e82118b9fd3fc8f9ae3b";
  }

  static const char* value(const ::ros_bridge::OpenDRPose2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88f7162365f7e821ULL;
  static const uint64_t static_value2 = 0x18b9fd3fc8f9ae3bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_bridge/OpenDRPose2D";
  }

  static const char* value(const ::ros_bridge::OpenDRPose2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright 2020-2022 OpenDR European Project\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message represents a full OpenDR human pose 2D as a list of keypoints\n"
"\n"
"Header header\n"
"\n"
"# The id of the pose\n"
"int32 pose_id\n"
"\n"
"# The pose detection confidence of the model\n"
"float32 conf\n"
"\n"
"# A list of a human 2D pose keypoints\n"
"OpenDRPose2DKeypoint[] keypoint_list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_bridge/OpenDRPose2DKeypoint\n"
"# Copyright 2020-2022 OpenDR European Project\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message contains all relevant information for an OpenDR human pose 2D keypoint\n"
"\n"
"# The kpt_name according to https://github.com/opendr-eu/opendr/blob/master/docs/reference/lightweight-open-pose.md#notes\n"
"string kpt_name\n"
"\n"
"# x and y pixel position on the input image, (0, 0) is top-left corner of image\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::ros_bridge::OpenDRPose2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose_id);
      stream.next(m.conf);
      stream.next(m.keypoint_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenDRPose2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_bridge::OpenDRPose2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_bridge::OpenDRPose2D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pose_id);
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    s << indent << "keypoint_list[]" << std::endl;
    for (size_t i = 0; i < v.keypoint_list.size(); ++i)
    {
      s << indent << "  keypoint_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.keypoint_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BRIDGE_MESSAGE_OPENDRPOSE2D_H
