// Generated by gencpp from file ros_bridge/OpenDRPose2DKeypoint.msg
// DO NOT EDIT!


#ifndef ROS_BRIDGE_MESSAGE_OPENDRPOSE2DKEYPOINT_H
#define ROS_BRIDGE_MESSAGE_OPENDRPOSE2DKEYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_bridge
{
template <class ContainerAllocator>
struct OpenDRPose2DKeypoint_
{
  typedef OpenDRPose2DKeypoint_<ContainerAllocator> Type;

  OpenDRPose2DKeypoint_()
    : kpt_name()
    , x(0)
    , y(0)  {
    }
  OpenDRPose2DKeypoint_(const ContainerAllocator& _alloc)
    : kpt_name(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _kpt_name_type;
  _kpt_name_type kpt_name;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> const> ConstPtr;

}; // struct OpenDRPose2DKeypoint_

typedef ::ros_bridge::OpenDRPose2DKeypoint_<std::allocator<void> > OpenDRPose2DKeypoint;

typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2DKeypoint > OpenDRPose2DKeypointPtr;
typedef boost::shared_ptr< ::ros_bridge::OpenDRPose2DKeypoint const> OpenDRPose2DKeypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator1> & lhs, const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator2> & rhs)
{
  return lhs.kpt_name == rhs.kpt_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator1> & lhs, const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce75e74f73663ed82a3235764bc7edf";
  }

  static const char* value(const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce75e74f73663edULL;
  static const uint64_t static_value2 = 0x82a3235764bc7edfULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_bridge/OpenDRPose2DKeypoint";
  }

  static const char* value(const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright 2020-2022 OpenDR European Project\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message contains all relevant information for an OpenDR human pose 2D keypoint\n"
"\n"
"# The kpt_name according to https://github.com/opendr-eu/opendr/blob/master/docs/reference/lightweight-open-pose.md#notes\n"
"string kpt_name\n"
"\n"
"# x and y pixel position on the input image, (0, 0) is top-left corner of image\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kpt_name);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenDRPose2DKeypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_bridge::OpenDRPose2DKeypoint_<ContainerAllocator>& v)
  {
    s << indent << "kpt_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.kpt_name);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BRIDGE_MESSAGE_OPENDRPOSE2DKEYPOINT_H
