batch_size: 128
frames_per_clip: 16
temporal_downsampling: 5
image_size: 224
learning_rate: 0.1
num_groups: 1
width_per_group: 64
width_factor: 2.0
depth_factor: 2.2
bottleneck_factor: 2.25
conv1_dim: 12
conv5_dim: 2048
use_channelwise_3x3x3: 1
dropout_rate: 0.5
head_activation: "softmax"
head_batchnorm: 0
fc_std_init: 0.01
final_batchnorm_zero_init: 1