name: Python Package Creation

on:
  push:
    tags:
      - v*.* # triggers on tags such as v1.1

# alternative: trigger on file change
# on:
#   push:
#     paths:
#       - '_version.py'


defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature-automatic-publish # to remove before merge
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        echo "Build wheel"
        ./bin/build_wheel.sh
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run : |
        echo "Upload"
        # twine upload --repository testpypi dist/*
